name: Build Samsung Galaxy M11 (LineageOS 20) + KSU

on:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "galaxy_m11"
  DEVICE_CODENAME : "a11q"

  CUSTOM_CMDS : ""
  EXTRA_CMDS : "LLVM=1 LLVM_IAS=1 CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi-"

  # Kernel Source
  KERNEL_SOURCE : "https://github.com/ifoodplayer/android_kernel_samsung_sdm450.git"
  KERNEL_BRANCH : "lineage-20"

  # Clang
  CLANG_SOURCE : "https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/13032023/neutron-clang-13032023.tar.zst"
  CLANG_BRANCH : ""

  # GCC
  GCC_GNU : false

  GCC_64_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9"
  GCC_64_BRANCH : "android-12.1.0_r27"

  GCC_32_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9"
  GCC_32_BRANCH : "android-12.1.0_r27"

  # Defconfig
  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "a11q_open_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  # KernelSU
  KERNELSU_SOURCE : "https://github.com/rsuntk/KernelSU"
  KERNELSU_BRANCH : "main"

  KERNELSU_AUTO_GET : "false"
  KERNELSU_AUTO_FORK : ""

  # SUSFS
  SUSFS_ENABLE : false
  SUSFS_FIXED : false

  # AnyKernel3
  AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH : "master"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "lineage20"

  # Python
  PYTHON_VERSION: "3"

  # Pack
  PACK_METHOD: "Anykernel3"
  PACK_KMODULES: "false"

  # KernelSU Method
  KERNELSU_METHOD: "manual"

  # Patches
  PATCHES_SOURCE: ""
  PATCHES_BRANCH: ""

  SUSFS_FOLDER_FIXED: ""
  SUSFS_PATCH_FIXED: ""

  REKERNEL_ENABLE: "false"

  # Hook
  HOOK_METHOD: "syscall"

  KERNEL_PATCH: "false"

  # KPM
  KPM_ENABLE: "false"
  KPM_INLINE: "false"
  KPM_KPATCH_NEXT: "false"
  KPM_PATCH_SOURCE: ""

  # Baseband Guard
  BASEBAND_GUARD_ENABLE: "false"
  BASEBAND_GUARD_BOOT: "false"

  # Hide Stuff
  HIDE_STUFF: "false"

  # DTB
  GENERATE_DTB: "false"
  GENERATE_CHIP: "qcom"

  # Debug
  BUILD_DEBUGGER: "false"
  SKIP_PATCH: "false"

  # Merge Config
  BUILD_OTHER_CONFIG: "false"
  MERGE_CONFIG_FILES: ""

  FREE_MORE_SPACE: "false"

jobs:
  build-kernel:
    name: Samsung Galaxy M11 Kernel Build
    runs-on: ubuntu-22.04

    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v4

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get necessary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🧰 Extra Kernel Options
        run: |
          cd $GITHUB_WORKSPACE/device_kernel
          echo "[+] Samsung Galaxy M11 build"

      - name: 🧰 Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: 🔒 Patch Kernel of Baseband Guard
        uses: ./.github/workflows/patch-baseband-guard

      - name: 🔧 Patch Hide Stuff
        uses: ./.github/workflows/patch-hide-stuff

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files